/**
 * shop action types
 */

const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_CILLECTIONS_FAILURE: "FETCH_CILLECTIONS_FAILURE",
};

export default ShopActionTypes;
